package model;

public enum TypKsiazki {
    SENSACJA, KRYMINAL, FANTASTYKA, THRILLER, HORROR, OBYCZAJOWA, PORADNIK, HISTORYCZNA, BIOGRAFIA, PODROZE, ROMANS, POPULARNONAUKOWA, MLODZIEZOWA, DZIECIECA, REPORTAZ, PODRECZNIK;
}
